#!/bin/bash

echo "  Downloading Github Repos"

if [[ ! -f ~/.ssh/id_rsa ]]; then
  ssh-keygen -t rsa -b 4096 -C "jgplane@gmail.com"
    eval "$(ssh-agent -s)"
  ssh-add -K ~/.ssh/id_rsa
  pbcopy < ~/.ssh/id_rsa.pub
  echo "New key copied to your clipboard"
  read -p "Add key to https://github.com/settings/keys, then press enter to continue"
fi

echo "    Done"
