#!/bin/bash

echo "  Setting Up Vim"

mkdir -p ~/.vim/swaps
mkdir -p ~/.vim/backups
mkdir -p ~/.vim/colors

if [[ -f  ~/.vim/colors/wintermute.vim ]]; then
  rm ~/.vim/colors/wintermute.vim
fi

curl -s -S https://raw.githubusercontent.com/jgplane/wintermute/master/wintermute.vim \
  --output ~/.vim/colors/wintermute.vim;\
echo "    Refreshed wintermute"

echo "    Done"
